# fly.toml app configuration file generated for bookkeeper-delicate-snow-8020 on 2024-08-01T20:58:50+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bookkeeper-delicate-snow-8020'
primary_region = 'nrt'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
